"""Codigos canonicos de erro para contratos de servico/aplicacao."""

from __future__ import annotations


class ErrorCode:
    """Catalogo central de codigos de erro operacionais."""

    # Historico / GAL sync
    HISTORY_PATH_REQUIRED = "HISTORY_PATH_REQUIRED"
    HISTORY_READ_FAILED = "HISTORY_READ_FAILED"
    HISTORY_ID_COLUMN_MISSING = "HISTORY_ID_COLUMN_MISSING"
    HISTORY_IDS_NOT_FOUND = "HISTORY_IDS_NOT_FOUND"
    HISTORY_WRITE_FAILED = "HISTORY_WRITE_FAILED"
    HISTORY_ACCESS_DENIED = "HISTORY_ACCESS_DENIED"
    HISTORY_CONTRACT_FALLBACK_USED = "HISTORY_CONTRACT_FALLBACK_USED"

    # Autenticacao / migracao legado
    AUTH_LEGACY_MIGRATION_FAILED = "AUTH_LEGACY_MIGRATION_FAILED"

    # Integracao GAL
    GAL_INTEGRATION_ERROR = "GAL_INTEGRATION_ERROR"
    GAL_LOGIN_ERROR = "GAL_LOGIN_ERROR"
    GAL_LOGIN_ELEMENT_NOT_FOUND = "GAL_LOGIN_ELEMENT_NOT_FOUND"
    GAL_LOGIN_NOT_CONFIRMED = "GAL_LOGIN_NOT_CONFIRMED"
    GAL_PAYLOAD_INVALID = "GAL_PAYLOAD_INVALID"

    # Sincronizacao de placa
    PLATE_SYNC_MERGE_FAILED = "PLATE_SYNC_MERGE_FAILED"
